apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: backend
  name: backend
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: backend
    spec:
      containers:
        - image: ilampa/rest-app:{tag}
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: docker-hub

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: api-endpoint
  selfLink: /api/v1/namespaces/default/services/api-endpoint
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32767
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}